# Generated by Django 4.1.2 on 2022-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletim',
            name='data_entrega',
            field=models.CharField(db_index=True, max_length=12, verbose_name='data_entrega'),
        ),
    ]
