# Generated by Django 4.1.2 on 2022-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_boletim_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasboletim',
            name='nota',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Nota'),
        ),
    ]
